In [1]:
import requests
import pandas as pd

In [25]:
#First Request
url = "https://redsky.target.com/redsky_aggregations/v1/web/plp_search_v2"

params = {
    "key": "9f36aeafbe60771e321a7cc95a78140772ab3e96",
    "category": "5xt7a",
    "channel": "WEB",
    "count": "24",
    "default_purchasability_filter": "true",
    "include_dmc_dmr": "true",
    "include_review_summarization": "false",
    "new_search": "false",
    "offset": "0",
    "page": "/c/5xt7a",
    "platform": "desktop",
    "pricing_store_id": "1771",
    "scheduled_delivery_store_id": "1771",
    "spellcheck": "true",
    "store_ids": "1771,1768,1113,3374,1792",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "visitor_id": "019653D8D8C80201910925902E2CD857",
    "zip": "52404"
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "Referer": "https://www.target.com/c/weights-strength-training-exercise-fitness-sports-outdoors/-/N-5xt7a?moveTo=product-list-grid"
}

response = requests.get(url, params=params, headers=headers)
# print(response.json())

In [68]:
#Page 2
import requests

url = "https://redsky.target.com/redsky_aggregations/v1/web/plp_search_v2"

params = {
    "key": "9f36aeafbe60771e321a7cc95a78140772ab3e96",
    "category": "5xt7a",
    "channel": "WEB",
    "count": "24",
    "default_purchasability_filter": "true",
    "include_dmc_dmr": "true",
    "include_review_summarization": "false",
    "new_search": "false",
    "offset": "24",  # Seule différence avec la première requête (était à 0 précédemment)
    "page": "/c/5xt7a",
    "platform": "desktop",
    "pricing_store_id": "1771",
    "scheduled_delivery_store_id": "1771",
    "spellcheck": "true",
    "store_ids": "1771,1768,1113,3374,1792",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "visitor_id": "019653D8D8C80201910925902E2CD857",
    "zip": "52404"
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "Referer": "https://www.target.com/c/weights-strength-training-exercise-fitness-sports-outdoors/-/N-5xt7a?moveTo=product-list-grid&Nao=24"
}

response = requests.get(url, params=params, headers=headers)
# print(response.json())

In [69]:
#Page 3
import requests

url = "https://redsky.target.com/redsky_aggregations/v1/web/plp_search_v2"

params = {
    "key": "9f36aeafbe60771e321a7cc95a78140772ab3e96",
    "category": "5xt7a",
    "channel": "WEB",
    "count": "24",
    "default_purchasability_filter": "true",
    "include_dmc_dmr": "true",
    "include_review_summarization": "false",
    "new_search": "false",
    "offset": "48",  # Troisième page de résultats (produits 49-72)
    "page": "/c/5xt7a",
    "platform": "desktop",
    "pricing_store_id": "1771",
    "scheduled_delivery_store_id": "1771",
    "spellcheck": "true",
    "store_ids": "1771,1768,1113,3374,1792",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "visitor_id": "019653D8D8C80201910925902E2CD857",
    "zip": "52404"
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "Referer": "https://www.target.com/c/weights-strength-training-exercise-fitness-sports-outdoors/-/N-5xt7a?moveTo=product-list-grid&Nao=48"
}

response = requests.get(url, params=params, headers=headers)
print(response.json())

In [26]:
#check status code
response

In [27]:
print(response.json())

{'data': {'search': {'search_recommendations': {'category_id': '5xt7a', 'related_categories': [{'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/-/N-davxk', 'title': 'Weights'}, {'url': '/c/exercise-fitness-sports-outdoors/-/N-5xt7d', 'title': 'Exercise & Fitness'}, {'url': '/c/kettlebells-strength-training-exercise-fitness-sports-outdoors/-/N-bv7kp', 'title': 'Kettlebells'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/tone-fitness/-/N-davxkZq643lei8o60', 'title': 'Weights tone-fitness'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/back/-/N-davxkZ5t1c7', 'title': 'Weights back'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/soozier/-/N-davxkZq643legs03i', 'title': 'Weights soozier'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/abilitations/-/N-davxkZ394u4', 'title': 'Weights abilitations'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/whizmax/-/N-davxkZq643lewbdqy', 'title': 'Weights whizmax'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/legs/-/N-davxkZ5t198', 'title': 'Weights legs'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/perfect-fitness/-/N-davxkZq643lebr3ap', 'title': 'Weights perfect-fitness'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/signature-fitness/-/N-davxkZq643le3q0he', 'title': 'Weights signature-fitness'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/hyperwear/-/N-davxkZq643lev517k', 'title': 'Weights hyperwear'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/best/-/N-davxkZ1rvvyys4rqi', 'title': 'Weights best'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/meister/-/N-davxkZq643lelapfa', 'title': 'Weights meister'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/all-in-motion/-/N-davxkZq643lerbxbq', 'title': 'Weights all-in-motion'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/prosourcefit/-/N-davxkZhx9bi', 'title': 'Weights prosourcefit'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/sunny-health-fitness/-/N-davxkZ8at5q', 'title': 'Weights sunny-health-fitness'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/arms/-/N-davxkZ5t1bd', 'title': 'Weights arms'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/synergee/-/N-davxkZq643lei4rqp', 'title': 'Weights synergee'}, {'url': '/c/weights-strength-training-exercise-fitness-sports-outdoors/lower-body/-/N-davxkZ5t1c5', 'title': 'Weights lower-body'}], 'related_queries': [{'url': '/s/weight+training', 'title': 'weight training'}, {'url': '/s/sports+training', 'title': 'sports training'}, {'url': '/s/grip+strength+trainer', 'title': 'grip strength trainer'}, {'url': '/s/fitness+weights', 'title': 'fitness weights'}, {'url': '/s/ankle+weights+for+exercise', 'title': 'ankle weights for exercise'}, {'url': '/s/light+weights', 'title': 'light weights'}, {'url': '/s/workout+equiptment', 'title': 'workout equiptment'}, {'url': '/s/workout+gear', 'title': 'workout gear'}, {'url': '/s/walking+weights', 'title': 'walking weights'}, {'url': '/s/empower+ankle+weights', 'title': 'empower ankle weights'}, {'url': '/s/fitness+gear+ankle+weights', 'title': 'fitness gear ankle weights'}, {'url': '/s/ankle+weights', 'title': 'ankle weights'}, {'url': '/s/lifting+weights+sets', 'title': 'lifting weights sets'}, {'url': '/s/core+workout', 'title': 'core workout'}, {'url': '/s/workout+clearance', 'title': 'workout clearance'}, {'url': '/s/workout+supplements', 'title': 'workout supplements'}, {'url': '/s/exercise+set', 'title': 'exercise set'}, {'url': '/s/fitness+gear+weight+sets', 'title': 'fitness gear weight sets'}, {'url': '/s/post+workout', 'title': 'post workout'}, {'url': '/s/racerback+workout', 'title': 'racerback workout'}]}, 'search_response': {'bread_crumb_list': [{'values': [{'label': 'Target', 'url': '/'}, {'category_id': '5xt85', 'label': 'Sports & Outdoors', 'url': '/c/sports-outdoors/-/N-5xt85'}, {'category_id': '5xt7d', 'label': 'Exercise & Fitness', 'url': '/c/exercise-fitness-sports-outdoors/-/N-5xt7d'}, {'category_id': '5xt7a', 'label': 'Strength Training', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/-/N-5xt7a'}]}], 'facet_list': [{'facet_id': 'd_channel', 'type': 'checkbox', 'display_name': 'Shipping & Pickup', 'expand': True, 'options': [{'display_name': 'buy online & pick up', 'id': '5zl7w', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/buy-online-pick-up/-/N-5xt7aZ5zl7w', 'value': 'buy online & pick up'}, {'display_name': 'get it today', 'id': 'n0nx1', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/get-it-today/-/N-5xt7aZn0nx1', 'value': 'get it today'}, {'display_name': 'in stores', 'id': '5zkty', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/in-stores/-/N-5xt7aZ5zkty', 'value': 'in stores'}, {'display_name': 'same day delivery', 'id': 'cl92v', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/same-day-delivery/-/N-5xt7aZcl92v', 'value': 'same day delivery'}, {'display_name': 'shipping', 'id': '5zktx', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/shipping/-/N-5xt7aZ5zktx', 'value': 'shipping'}, {'display_name': 'include out of stock', 'id': 'fwtfr', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/include-out-of-stock/-/N-5xt7aZfwtfr', 'value': 'include out of stock'}]}, {'facet_id': 'd_deals', 'type': 'checkbox', 'display_name': 'Deals', 'expand': True, 'options': [{'display_name': 'All Deals', 'id': 'akkos', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/all-deals/-/N-5xt7aZakkos', 'value': 'all deals'}, {'display_name': 'Sale', 'id': '5tdv0', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/sale/-/N-5xt7aZ5tdv0', 'value': 'sale'}, {'display_name': 'New Lower Price', 'id': '71vf7', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/new-lower-price/-/N-5xt7aZ71vf7', 'value': 'new lower price'}]}, {'facet_id': 'd_item_type_all', 'type': 'checkbox', 'display_name': 'Type', 'expand': True, 'options': [{'display_name': 'Body Weights', 'id': 'j3x7k', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/body-weights/-/N-5xt7aZj3x7k', 'value': 'body weights'}, {'display_name': 'Classic Medicine Balls', 'id': 'al25lfqxb3p', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/classic-medicine-balls/-/N-5xt7aZal25lfqxb3p', 'value': 'classic medicine balls'}, {'display_name': 'Dumbbells', 'id': '5k0pg', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/dumbbells/-/N-5xt7aZ5k0pg', 'value': 'dumbbells'}, {'display_name': 'Fitness Gloves', 'id': 'uv8zt', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/fitness-gloves/-/N-5xt7aZuv8zt', 'value': 'fitness gloves'}, {'display_name': 'Flat Bands', 'id': 'mrx3q', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/flat-bands/-/N-5xt7aZmrx3q', 'value': 'flat bands'}, {'display_name': 'Gloves', 'id': '5t066', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/gloves/-/N-5xt7aZ5t066', 'value': 'gloves'}, {'display_name': 'Hard Medicine Balls', 'id': 'al25lfhzgu4', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/hard-medicine-balls/-/N-5xt7aZal25lfhzgu4', 'value': 'hard medicine balls'}, {'display_name': 'Home Gym Attachments', 'id': 'tgs01', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/home-gym-attachments/-/N-5xt7aZtgs01', 'value': 'home gym attachments'}, {'display_name': 'Home Gyms', 'id': '55p9d', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/home-gyms/-/N-5xt7aZ55p9d', 'value': 'home gyms'}, {'display_name': 'Kettlebells', 'id': 'pf64n', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/kettlebells/-/N-5xt7aZpf64n', 'value': 'kettlebells'}, {'display_name': 'Knee Pads', 'id': 'qs5rr', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/knee-pads/-/N-5xt7aZqs5rr', 'value': 'knee pads'}, {'display_name': 'Medicine Balls', 'id': '55p8g', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/medicine-balls/-/N-5xt7aZ55p8g', 'value': 'medicine balls'}, {'display_name': 'Pilates Machines', 'id': '55owl', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/pilates-machines/-/N-5xt7aZ55owl', 'value': 'pilates machines'}, {'display_name': 'Resistance Band Handles', 'id': 'al25lfpmxj6', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/resistance-band-handles/-/N-5xt7aZal25lfpmxj6', 'value': 'resistance band handles'}, {'display_name': 'Resistance Bands', 'id': '55owk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/resistance-bands/-/N-5xt7aZ55owk', 'value': 'resistance bands'}, {'display_name': 'Resistance Tubes', 'id': 'j3nyj', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/resistance-tubes/-/N-5xt7aZj3nyj', 'value': 'resistance tubes'}, {'display_name': 'Round Bands', 'id': '9l85w', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/round-bands/-/N-5xt7aZ9l85w', 'value': 'round bands'}, {'display_name': 'Slam Medicine Balls', 'id': 'al25lf38omk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/slam-medicine-balls/-/N-5xt7aZal25lf38omk', 'value': 'slam medicine balls'}, {'display_name': 'Soft Medicine Balls', 'id': 'al25lfb1fmn', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/soft-medicine-balls/-/N-5xt7aZal25lfb1fmn', 'value': 'soft medicine balls'}, {'display_name': 'Weight Accessories', 'id': '12boa', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weight-accessories/-/N-5xt7aZ12boa', 'value': 'weight accessories'}, {'display_name': 'Weight Bars', 'id': 'j2b0v', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weight-bars/-/N-5xt7aZj2b0v', 'value': 'weight bars'}, {'display_name': 'Weight Benches', 'id': '2rcad', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weight-benches/-/N-5xt7aZ2rcad', 'value': 'weight benches'}, {'display_name': 'Weight Plates', 'id': '4yngo', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weight-plates/-/N-5xt7aZ4yngo', 'value': 'weight plates'}, {'display_name': 'Weight Racks', 'id': '4k1w', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weight-racks/-/N-5xt7aZ4k1w', 'value': 'weight racks'}, {'display_name': 'Weightlifting Gloves', 'id': '9crt4', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/weightlifting-gloves/-/N-5xt7aZ9crt4', 'value': 'weightlifting gloves'}, {'display_name': 'Workout Bars', 'id': '18nwu', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/workout-bars/-/N-5xt7aZ18nwu', 'value': 'workout bars'}, {'display_name': 'Wrist Wraps', 'id': 'al25lf5ut9l', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/wrist-wraps/-/N-5xt7aZal25lf5ut9l', 'value': 'wrist wraps'}]}, {'facet_id': 'd_product_weight_lbs', 'type': 'checkbox', 'display_name': 'Weight', 'expand': True, 'options': [{'display_name': '0 &nbsp;&ndash;&nbsp; 5 lbs', 'id': '4cdlw', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/0-5-lbs/-/N-5xt7aZ4cdlw', 'value': '0000 0 - 5 lbs'}, {'display_name': '5 &nbsp;&ndash;&nbsp; 10 lbs', 'id': '3jbx7', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/5-10-lbs/-/N-5xt7aZ3jbx7', 'value': '0001 5 - 10 lbs'}, {'display_name': '10 &nbsp;&ndash;&nbsp; 15 lbs', 'id': 'dq6it', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/10-15-lbs/-/N-5xt7aZdq6it', 'value': '0002 10 - 15 lbs'}, {'display_name': '15 &nbsp;&ndash;&nbsp; 20 lbs', 'id': 'pyi1w', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/15-20-lbs/-/N-5xt7aZpyi1w', 'value': '0003 15 - 20 lbs'}, {'display_name': '20 &nbsp;&ndash;&nbsp; 25 lbs', 'id': 'l0q3h', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/20-25-lbs/-/N-5xt7aZl0q3h', 'value': '0004 20 - 25 lbs'}, {'display_name': '25 &nbsp;&ndash;&nbsp; 30 lbs', 'id': 'r4iy1', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/25-30-lbs/-/N-5xt7aZr4iy1', 'value': '0005 25 - 30 lbs'}, {'display_name': '30 &nbsp;&ndash;&nbsp;35 lbs', 'id': '9rjgw', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/30-35-lbs/-/N-5xt7aZ9rjgw', 'value': '0006 30 -35 lbs'}, {'display_name': '35 &nbsp;&ndash;&nbsp; 40 lbs', 'id': '5sbmi', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/35-40-lbs/-/N-5xt7aZ5sbmi', 'value': '0007 35 - 40 lbs'}, {'display_name': '40 &nbsp;&ndash;&nbsp; 45 lbs', 'id': 'nljk1', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/40-45-lbs/-/N-5xt7aZnljk1', 'value': '0008 40 - 45 lbs'}, {'display_name': '45 &nbsp;&ndash;&nbsp; 50 lbs', 'id': '3mrl9', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/45-50-lbs/-/N-5xt7aZ3mrl9', 'value': '0009 45 - 50 lbs'}, {'display_name': '50 &nbsp;&ndash;&nbsp; 55 lbs', 'id': 'sccyu', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/50-55-lbs/-/N-5xt7aZsccyu', 'value': '0010 50 - 55 lbs'}, {'display_name': '55 &nbsp;&ndash;&nbsp; 60 lbs', 'id': '6l9rq', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/55-60-lbs/-/N-5xt7aZ6l9rq', 'value': '0011 55 - 60 lbs'}, {'display_name': '60 &nbsp;&ndash;&nbsp; 65 lbs', 'id': 'kg9gs', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/60-65-lbs/-/N-5xt7aZkg9gs', 'value': '0012 60 - 65 lbs'}, {'display_name': '10 lbs', 'id': '2ay7c', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/10-lbs/-/N-5xt7aZ2ay7c', 'value': '0013 10 lbs'}]}, {'facet_id': 'd_brand_all', 'type': 'checkbox', 'display_name': 'Brand', 'expand': False, 'options': [{'display_name': 'AB Dolly', 'id': 'q643lel5izk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/ab-dolly/-/N-5xt7aZq643lel5izk', 'value': 'ab dolly'}, {'display_name': 'Abilitations', 'id': '394u4', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/abilitations/-/N-5xt7aZ394u4', 'value': 'abilitations'}, {'display_name': 'AeroPilates', 'id': 'q643lewovi1', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/aeropilates/-/N-5xt7aZq643lewovi1', 'value': 'aeropilates'}, {'display_name': 'All In Motion', 'id': 'q643lerbxbq', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/all-in-motion/-/N-5xt7aZq643lerbxbq', 'value': 'all in motion'}, {'display_name': 'Amber Sports', 'id': 'q643le748lc', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/amber-sports/-/N-5xt7aZq643le748lc', 'value': 'amber sports'}, {'display_name': 'Anchor', 'id': '5x10v', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/anchor/-/N-5xt7aZ5x10v', 'value': 'anchor'}, {'display_name': 'Bala', 'id': 'q643leq5jv5', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bala/-/N-5xt7aZq643leq5jv5', 'value': 'bala'}, {'display_name': 'BalanceFrom Fitness', 'id': 'q643leuv6zm', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/balancefrom-fitness/-/N-5xt7aZq643leuv6zm', 'value': 'balancefrom fitness'}, {'display_name': 'Best Choice Products', 'id': 'q643le2dwgz', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/best-choice-products/-/N-5xt7aZq643le2dwgz', 'value': 'best choice products'}, {'display_name': 'Best Fitness', 'id': 'q643le2ngs4', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/best-fitness/-/N-5xt7aZq643le2ngs4', 'value': 'best fitness'}, {'display_name': 'BestParts', 'id': 'q643lesw28z', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bestparts/-/N-5xt7aZq643lesw28z', 'value': 'bestparts'}, {'display_name': 'BeyondBarre', 'id': '9lt05', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/beyondbarre/-/N-5xt7aZ9lt05', 'value': 'beyondbarre'}, {'display_name': 'BFR Bands', 'id': 'q643lezhbjc', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bfr-bands/-/N-5xt7aZq643lezhbjc', 'value': 'bfr bands'}, {'display_name': 'Bintiva', 'id': 'q643le32gsl', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bintiva/-/N-5xt7aZq643le32gsl', 'value': 'bintiva'}, {'display_name': 'Bionic', 'id': 'q643lefn064', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bionic/-/N-5xt7aZq643lefn064', 'value': 'bionic'}, {'display_name': 'Bionic Body', 'id': '4ycgh', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bionic-body/-/N-5xt7aZ4ycgh', 'value': 'bionic body'}, {'display_name': 'Bionic Gloves', 'id': 'e2xsi', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bionic-gloves/-/N-5xt7aZe2xsi', 'value': 'bionic gloves'}, {'display_name': 'Blogilates', 'id': 'q643ler8trk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/blogilates/-/N-5xt7aZq643ler8trk', 'value': 'blogilates'}, {'display_name': 'Bob and Brad', 'id': 'q643leegx53', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bob-and-brad/-/N-5xt7aZq643leegx53', 'value': 'bob and brad'}, {'display_name': 'Body Sport', 'id': 'q643le9c0lg', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/body-sport/-/N-5xt7aZq643le9c0lg', 'value': 'body sport'}, {'display_name': 'Body-Solid', 'id': '5d7tk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/body-solid/-/N-5xt7aZ5d7tk', 'value': 'body-solid'}, {'display_name': 'BOSU', 'id': 'hdlye', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bosu/-/N-5xt7aZhdlye', 'value': 'bosu'}, {'display_name': 'Bowflex', 'id': '56cti', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/bowflex/-/N-5xt7aZ56cti', 'value': 'bowflex'}, {'display_name': "Britt's Knits", 'id': 'q643le8z03b', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/britt-s-knits/-/N-5xt7aZq643le8z03b', 'value': "britt's knits"}, {'display_name': 'CanDo', 'id': 'vi8e0', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/cando/-/N-5xt7aZvi8e0', 'value': 'cando'}, {'display_name': 'CAP', 'id': 'q643levslw0', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/cap/-/N-5xt7aZq643levslw0', 'value': 'cap'}, {'display_name': 'CAP Strength', 'id': 'q643lejgiqj', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/cap-strength/-/N-5xt7aZq643lejgiqj', 'value': 'cap strength'}, {'display_name': 'Capezio', 'id': 'q643le8gsya', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/capezio/-/N-5xt7aZq643le8gsya', 'value': 'capezio'}, {'display_name': 'CENTR', 'id': 'q643le2m6pn', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/centr/-/N-5xt7aZq643le2m6pn', 'value': 'centr'}, {'display_name': 'Competitor', 'id': '56fjk', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/competitor/-/N-5xt7aZ56fjk', 'value': 'competitor'}, {'display_name': 'Costway', 'id': 'q643lefe4e4', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/costway/-/N-5xt7aZq643lefe4e4', 'value': 'costway'}, {'display_name': 'Cubii', 'id': 'q643le1nq70', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/cubii/-/N-5xt7aZq643le1nq70', 'value': 'cubii'}, {'display_name': 'DartActive', 'id': 'q643lepbwd', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/dartactive/-/N-5xt7aZq643lepbwd', 'value': 'dartactive'}, {'display_name': 'Dexmalle', 'id': 'q643le8bkzs', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/dexmalle/-/N-5xt7aZq643le8bkzs', 'value': 'dexmalle'}, {'display_name': 'DOMETOUR', 'id': 'q643led59fb', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/dometour/-/N-5xt7aZq643led59fb', 'value': 'dometour'}, {'display_name': 'Egg Weights', 'id': 'q643lexbpfh', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/egg-weights/-/N-5xt7aZq643lexbpfh', 'value': 'egg weights'}, {'display_name': 'ER KANG', 'id': 'q643lex04di', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/er-kang/-/N-5xt7aZq643lex04di', 'value': 'er kang'}, {'display_name': 'Exerband', 'id': 'q643leai12l', 'url': '/c/weight-training-exercise-fitness-sports-outdoors/exerband/-/N-5xt7aZq643leai12l', 'value': 'exerband'}, {'display_n

In [28]:
#Output Keys
results_json = response.json()
results_json.keys()

dict_keys(['data', 'extensions'])

In [38]:
results_items=results_json['data']['search']['products']
len(results_items)

24

In [41]:
#Product Title
results_items[0]['item']['product_description']['title'].replace('&#8482;','')

'Basic Hand Weight Set Pink/White/Magenta - All In Motion'

In [44]:
#Product Price
results_items[0]['price']['current_retail']

49.99

In [47]:
#Product Brand Name
results_items[0]['item']['primary_brand']['name']

'All In Motion'

In [51]:
#Product Ratings 
results_items[0]['ratings_and_reviews']['statistics']['rating']['average']

4.65

In [52]:
#Product Ratings Count
results_items[0]['ratings_and_reviews']['statistics']['rating']['count']

238

In [60]:
products_title=[]
price=[]
brand=[]
rating_avg=[]
rating_count=[]

for result in results_items:
    try:      
        products_title.append(result['item']['product_description']['title'].replace('&#8482;',''))
    except:   
        products_title.append('')
        
    try:    
        price.append(result['price']['current_retail'])
    except:   
        price.append('')
      
    try:
        brand.append(result['item']['primary_brand']['name'])
    except:   
        brand.append('')
        
    try:   
        rating_avg.append(result['ratings_and_reviews']['statistics']['rating']['average'])
    except:   
        rating_avg.append('')  
        
        
    try:
        rating_count.append(result['ratings_and_reviews']['statistics']['rating']['count'])
    except:   
        rating_count.append('')

In [65]:
target_df = pd.DataFrame({'Products_title':products_title,'Price':price,'brand':brand,'rating_avg':rating_avg,'rating_count':rating_count})

In [66]:
target_df

,Products_title,Price,brand,rating_avg,rating_count
0,Basic Hand Weight Set Pink/White/Magenta - All...,49.99,All In Motion,4.65,238
1,Neoprene Dumbbell 20lbs Blue - All In Motion,34.99,All In Motion,,
2,Hex Dumbbell 35lbs Black - All In Motion,54.99,All In Motion,,
3,Adjustable Dumbbell 25lbs - All In Motion,99.99,All In Motion,4.82,44
4,Bowflex SelectTech 552 Dumbbell - Black,199.99,Bowflex,4.45,101
5,Ankle Weights Anti-microbial 2.5lbs 2pc - All ...,24.99,All In Motion,4.72,107
6,Ankle Weights Anti-microbial 4lbs 2pc - All In...,22.99,All In Motion,4.69,135
7,Wrist Weights Anti-microbial 1.5lbs 2pc - All ...,17.99,All In Motion,4.64,95
8,Men&#39;s Strength Training Gloves Black M - A...,9.99,All In Motion,,
9,Wrist Weights Anti-micorbial 2.5lbs 2pc - All ...,19.99,All In Motion,4.51,75
10,Weighted Vest 8lb - All In Motion,34.99,All In Motion,4.68,74
11,Women&#39;s Strength Training Gloves Purple XS...,9.99,All In Motion,,
12,Kettlebell 25lb Gray - All In Motion,63.99,All In Motion,,
13,Push Up Bar - All In Motion,19.99,All In Motion,4.53,36
14,Loop Band Kit Blue - All In Motion,12.49,All In Motion,3.28,359
15,Flat Band Kit Blue - All In Motion,9.29,All In Motion,4.27,181
16,Premium Loop Band Kit - All In Motion,12.99,All In Motion,3.28,40
17,Premium Flat Band Kit - All In Motion,10.99,All In Motion,4.16,25
18,Fabric Round Hip Band Set - All In Motion,17.99,All In Motion,4.75,28
19,Adjustable Weight Bench - All In Motion,99.99,All In Motion,4.48,17
20,Multi-function Pull-Up Weight Bar 300lbs - All...,19.99,All In Motion,4.05,40
21,Medicine Ball 10lbs - Blue - All In Motion,24.99,All In Motion,4.83,17
22,Marcy 150 LB Stack Home Gym,599.99,Marcy,4.53,17
23,Total Gym XLS Universal Total Body Home Gym Wo...,1099.99,Total Gym,,

### Multiple Pages

In [70]:
url = "https://redsky.target.com/redsky_aggregations/v1/web/plp_search_v2"
products_title=[]
price=[]
brand=[]
rating_avg=[]
rating_count=[]

for i in range(0,240,24):

    params = {
        "key": "9f36aeafbe60771e321a7cc95a78140772ab3e96",
        "category": "5xt7a",
        "channel": "WEB",
        "count": "24",
        "default_purchasability_filter": "true",
        "include_dmc_dmr": "true",
        "include_review_summarization": "false",
        "new_search": "false",
        "offset": str(i),
        "page": "/c/5xt7a",
        "platform": "desktop",
        "pricing_store_id": "1771",
        "scheduled_delivery_store_id": "1771",
        "spellcheck": "true",
        "store_ids": "1771,1768,1113,3374,1792",
        "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
        "visitor_id": "019653D8D8C80201910925902E2CD857",
        "zip": "52404"
    }

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
        "Referer": "https://www.target.com/c/weights-strength-training-exercise-fitness-sports-outdoors/-/N-5xt7a?moveTo=product-list-grid"
    }
    
    #response
    response = requests.get(url, params=params, headers=headers)
    
    results_json = response.json()
    
    results_items=results_json['data']['search']['products']

    
    for result in results_items:
        try:      
            products_title.append(result['item']['product_description']['title'].replace('&#8482;',''))
        except:   
            products_title.append('')

        try:    
            price.append(result['price']['current_retail'])
        except:   
            price.append('')

        try:
            brand.append(result['item']['primary_brand']['name'])
        except:   
            brand.append('')

        try:   
            rating_avg.append(result['ratings_and_reviews']['statistics']['rating']['average'])
        except:   
            rating_avg.append('')  


        try:
            rating_count.append(result['ratings_and_reviews']['statistics']['rating']['count'])
        except:   
            rating_count.append('')

In [71]:
target_df = pd.DataFrame({'Products_title':products_title,'Price':price,'brand':brand,'rating_avg':rating_avg,'rating_count':rating_count})

In [72]:
target_df

,Products_title,Price,brand,rating_avg,rating_count
0,Basic Hand Weight Set Pink/White/Magenta - All...,49.99,All In Motion,4.65,238
1,Dumbbell 15lbs Blue - All In Motion,25.99,All In Motion,,
2,Hex Dumbbell 25lbs Black - All In Motion,42.99,All In Motion,,
3,Adjustable Dumbbell 25lbs - All In Motion,99.99,All In Motion,4.82,44
4,Bowflex SelectTech 552 Dumbbell - Black,199.99,Bowflex,4.45,101
...,...,...,...,...,...
235,"THERABAND Resistance Band Loop, 12 IN, Yellow,...",7.92,TheraBand,0.0,0
236,"""iMountek Yoga Resistance Band Set – 3 Non-Tox...",14.89,iMountek,0.0,0
237,Iron Neck Alpha Workout Harness | Improve Neck...,59.00,Iron Neck,0.0,0
238,Rawlings Baseball Resistance Training Band wit...,29.99,Rawlings,,
239,Lifeline Train Station Resistance Band Kit,27.99,Lifeline,4.75,8

In [74]:
#Store results in Excel
target_df.to_excel('target_multiple_pages.xlsx',index=False)